name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos6
          - centos7
          - ubuntu1604
          - ubuntu1804
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: cache cmake build files
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ matrix.tag }}-build-release
      - name: build and test in docker container
        timeout-minutes: 90
        run: docker run --rm -v $(pwd):/home/nebula vesoft/nebula-dev:${{ matrix.os }} ./ci/scripts/build.sh build_type=Release
